# Setup
title:        Souvic Chakraborty (শৌভিক চক্রবর্তী)
tagline:      PhD Scholar (TCS Research Fellow), CSE, IIT Kharagpur
baseurl:      "https://souvic.github.io/"
paginate:     1
locale:       "en"
google_analytics: UA-158508962-1
# About/contact
author:
  name:       Souvic Chakraborty
  url:        #

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
