# Setup
title:        Gourab Kumar Patro (<script >abcd</script>)
tagline:      PhD Scholar, CSE, IIT Kharagpur
baseurl:      "https://gourabkumarpatro.github.io/"
paginate:     1
locale:       "en"
google_analytics: UA-131017147-1
# About/contact
author:
  name:       Gourab Kumar Patro
  url:        #

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
