# Setup
title:        Gourab Kumar Patro
tagline:      PhD Scholar, CSE, IIT Kharagpur
baseurl:      "https://gourabkumarpatro.github.io/"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Gourab Kumar Patro
  url:        #

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
