# Setup
title:        Gourab Kumar Patro
tagline:      PhD Scholar, CSE, IIT Kharagpur
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Gourab Kumar Patro
  url:        http://www.gourabkumarpatro.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
