# Setup
title:        Gourab Kumar Patro गौरब कुमार पात्रो
tagline:      PhD Scholar (TCS Research Fellow), CSE, IIT Kharagpur
baseurl:      "https://gourabkumarpatro.github.io/"
paginate:     1
locale:       "en"
google_analytics: UA-131017147-1
# About/contact
author:
  name:       Gourab Kumar Patro
  url:        #

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
