# Setup
title:        Souvic Chakraborty (শৌভিক চক্রবর্তী)
tagline:      Founder · VideoDubber.ai · SEOBlogger.ai · Discorder.tools
baseurl:      "https://souvic.github.io/"
locale:       "en"
google_analytics: UA-158508962-1
# About/contact
author:
  name:       Souvic Chakraborty
  url:        #

#Others
markdown: kramdown
